G_zone/G_zone/urls.py
from tkinter.font import names

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from eshop import views





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path("accounts/", include("django.contrib.auth.urls")), 

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'), 

    path('contact/', views.contact_view, name='contact'),
    path('contact/success/', views.contact_success, name='contact_success'),

    path('checkout/', views.checkout, name="checkout"),

    


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

G_zone/eshop/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
import datetime

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,default='')
    sub_category = models.ForeignKey(SubCategory,on_delete=models.CASCADE,null=False,default='')
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=False,default='')
    image = models.ImageField(upload_to='static/pimage')
    name = models.CharField(max_length=150)
    desc = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=12,decimal_places=2,default='0')
    pre_price = models.DecimalField(max_digits=12, decimal_places=2,default='0')
    date =models.DateField(auto_now_add=True)
                
    def __str__(self):
         return self.name

class Slider(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,default='')
    name = models.CharField(max_length=150)
    img = models.ImageField(upload_to='static/slider/images')
    date = models.DateField(auto_now_add=True)

    def __str__(self):
         return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    


class Order(models.Model):
    image = models.ImageField(upload_to='static/order_image')
    product = models.CharField(max_length=150, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = price = models.DecimalField(max_digits=12,decimal_places=2,default='0')
    quantity = models.CharField(max_length=5)
    total = models.DecimalField(max_digits=12,decimal_places=2,default='0')
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, default='0')
    date = models.DateField(default=datetime.datetime.today)

    def __str__(self):
        return self.product

G_zone/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Girl's Zone</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.main.css' %}">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
<body>
<div class"fixed-top">
    <div class="container-fluid" id="tmanu">

            <div  id="item2">
              <a href="#" class=""><i class="bi bi-envelope-fill"> Email</i></a>
              <span class="mx-md-2 d-inline-block"></span>
              <a href="#" class=""><span > <i class="bi bi-telephone-fill"></i>+88-01818429056</span></a>
            </div>
             <div  id="item3">
              
    <a class="text-reset me-3" href="{% url 'cart_detail' %}">
        <i class="fas fa-shopping-cart"></i>
        <span class="badge rounded-pill badge-notification bg-danger">{{request.session.cart|length}}</span>
      </a>
      <a class="text-reset me-3" href="#">
      <i class="fas fa-bell"></i>
    </a>
  </div>
  <div class="item4">
          
      {% if user.is_authenticated %}
           <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-success btn-sm" type="submit">Log Out</button>
           </form>

           
          {% else %}


           <a class="btn btn-outline-success btn-sm" href="{% url "login" %}">Login</a>
            {% endif %}
          </div>
    </div>

              

            </div>

        

        </div>


      
  <nav class="navbar navbar-expand-lg  px-5 bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Girl's Zone</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "home"%}">Home</a>
        </li>
           
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "signup"%}">SignUp</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url "contact"%}">Contact Us</a>
        </li>
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    
    
  </div>
</nav>
<section class="text-center p-5">
   <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
     <div class="carousel-inner">
           <div class="carousel-item active">
             <img src="https://trishscully.com/cdn/shop/collections/slider-1_1.webp?v=1717152426&width=1400" class="d-block w-100" alt="img 2">
        </div>
             {% for sl in slider %}
               <div class="carousel-item">
                 <img src="{{sl.img}}" class="d-block w-100" alt="img 1">
               </div>
             {% endfor %}
   
      </div>
  
    </div>
    </section>
  </div>
</div>

{% block content %}


{% endblock content %}

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>



<!-- Modal Producet Dtails -->
 {%for i in product %}
<div class="modal fade" id="exampleModal-{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Producet Dtails</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
    <div class="row border my-1">
      <div class="col-sm-3 col-md-6 col-lg-6 text-align-first p-0 border">
       <img src="{{i.image}}" class="rounded" width="200px" height="300px" alt="...">
      </div>
      <div class="col-sm-3 col-md-6 col-lg-6 text-align-first ms-auto">
       <p>Product Name:{{i.name}}</p>
       <p>Price:{{i.price}}</p>
       <p>Details:{{i.details}}</p>
      </div>
    </div>
    </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
       <a href="{% url 'cart_add' i.id %}" class="btn btn-primary">Add To Cart</a>
      </div>
    </div>
  </div>
</div>
{%endfor%}

<footer>
  <br>
  <br>
  <p>Author: MD MERAZ PASHA<br>
  <a href="mailto:bitcc08@e.com">bitcc08@e.comm</a></p>
</footer>
</body>
</html>

G_zone/templates/base2.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Girl's Zone</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.main.css' %}">
    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
.checked {
  color: orange;
}
<style>
.checked {
  color: orange;
}
.cart-item img {
     max-width: 100px;
     height: auto;
 }

 .quantity-input {
     width: 40px;
     height: 10px;
 }



 .cart-summary {
     background-color: #f8f9fa;
     border-radius: 10px;
 }
</style>


 <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f8ff;
            color: #333;
            
        }
        h1 {
            font-size: 2em;
            color: green;
            font-family: 'Times New Roman', Times, serif;
        }
        form {
            display: inline-block;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        
        button[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 5px 10px;
            border: none;
            font-size: 15px;
            font-weight: bold;
            border-radius: 5px;
            cursor: pointer;
            font-family: 'Times New Roman', Times, serif;
        }
        button[type="submit"]:hover {
            background-color: #45a049;
        }
      form {
  border: 3px solid #f1f1f1;
}

/* Full-width inputs */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

/* Add a hover effect for buttons */
button:hover {
  opacity: 0.8;
}

/* Extra style for the cancel button (red) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the avatar image inside this container */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

/* Avatar image */
img.avatar {
  width: 40%;
  border-radius: 50%;
}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}
form {
  border: 3px solid #f1f1f1;
}

/* Full-width inputs */
input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

/* Add a hover effect for buttons */
button:hover {
  opacity: 0.8;
}

/* Extra style for the cancel button (red) */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

/* Center the avatar image inside this container */
.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

/* Avatar image */
img.avatar {
  width: 40%;
  border-radius: 50%;
}

/* Add padding to containers */
.container {
  padding: 16px;
}

/* The "Forgot password" text */
span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
    display: block;
    float: none;
  }
  .cancelbtn {
    width: 100%;
  }
}

    </style>
    <style>
footer {
  text-align: center;
  padding: 3px;
  background-color: black;
  color: white;
}

</style>
  </head>
<body>


<div class="container">
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Girl's Zone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "home"%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>




</div>
</div>


{% block content %} {% endblock content %}

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<footer>
  <br>
  <br>
  <p>Author: MD MERAZ PASHA<br>
  <a href="mailto:bitcc08@e.com">bitcc08@e.comm</a></p>
</footer>
</body>
</html>

G_zone/templates/checkout.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>Your order has been submited successfully!</h1>
<p>Click Here Go To : <a href="{% url "home"%}">Home</a></p>

</body>
</html>

G_zone/templates/contact.html
{% extends 'base2.html' %}
{% block content %}




<section class="justify-content-center">

<div class="continer">

 <div class="row justify-content-center">
    <div class="col-md-4">
     <h1>Contact Us</h1>
     <form method="post">
         {% csrf_token %}
         {{ form }}
         <div class="form-actions">
              <button type="submit">Send</button>
         </div>
     </form>
     </div>
  </div>

</div>


</section>

{% endblock %}

G_zone/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
<div class="row border">
    <div class="col-sm-3 col-md-3 col-lg-3">
        <div  class="list-group  mt-4">
            
            <a href="#" class="list-group-item list-group-item-action active">Category</a>
            {% for cat in category %}
        <a href="#{{cat.id}}" class="list-group-item list-group-item-action" data-bs-toggle="collapse" aria-controls="{{cat.id}}">
{{cat.name}}
  </a>
<div class="collapse" id="{{cat.id}}">
  
  {% for i in cat.subcategory_set.all %}
   <a href="/?category={{i.id}}" class="list-group-item d-flex justify-content-between align-items-center">
    {{i.name}}</a>
    
  {% endfor%}
   
</div>
            {% endfor %}
            
</div>

    </div>
    <div class="col-sm-4 col-md-9 col-lg-9">
        <div class="row"><div class="col-sm-12">Dress</div></div>
    <div class="row border">
      {% for pr in product %}
        <div class="col-sm-4 col-lg-3 col-md-2 justify-content-first d-flex  mt-1">
            <div class="card" style="width: 18rem;">
  <img src="{{pr.image}}" class="card-img-top" height="250px" alt="...">
  <div class="card-body">
      <p class="card-text">{{pr.name}}</p>
      <p>Offer Price:BDT {{pr.price}} <br>
          Pre Price:BDT <del>{{pr.price}}</del>&nbsp;&nbsp;<span class="btn btn-danger  rounded-circle"> Off<br>-13%</span><br>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
<span class="fa fa-star checked"></span>
    <span class="fa fa-star"></span></p>

      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal-{{forloop.counter}}">
       Details
     </button>
      <a href="{% url 'cart_add' pr.id %}" class="btn btn-primary">Add To Cart</a>
  </div>
</div>
</div>
{% endfor %}
        
        
        
        </div>
    </div>

 
</div>



{% endblock content%}

G_zone/templates/success.html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>Your message has been submited successfully!</h1>
<p>Click Here Go To : <a href="{% url "home"%}">Home</a></p>

</body>
</html>